Avoid local copy of decomp_info objects
xcompact3d/2decomp-fft pull request #60
Opened 2022-09-26 11:13 UTC by mathrack

2022-09-28 12:01 UTC, pbartholomew08 requested changes
See above discussions

2022-09-28 12:02 UTC, mathrack commented on src/fft_common.f90
> +TYPE(DECOMP_INFO), pointer, save :: ph=>null()  ! physical space
This modification is limited to the FFT engine. User code do not have access to this decomp_info object.

2022-09-28 12:26 UTC, mathrack commented on src/fft_common.f90
> +! FIXME this is already defined in the module decomp_2d
This FIXME should be in another PR, no fix is proposed here.

2022-09-28 12:26 UTC, mathrack commented on src/fft_common.f90
> +! FIXME this is already available in the module decomp_2d
This FIXME should be in another PR, no fix is proposed here.

2022-09-28 12:27 UTC, mathrack commented on src/fft_fftw3_f03.f90
> +  ! FIXME this is already available in the module decomp_2d
This FIXME should be in another PR, no fix is proposed here.

2022-09-28 12:36 UTC, pbartholomew08 commented on src/decomp_2d.f90
> +  ! FIXME avoid a copy and return a pointer to decomp_main
ok this should be an obvious change to any code users

2022-09-28 12:47 UTC, mathrack commented on src/decomp_2d.f90
> +  ! FIXME avoid a copy and return a pointer to decomp_main
If they have a pointer to the object decom_main, they have the power to finalize it. With great power comes great responsibility.

2022-10-04 10:23 UTC, mathrack commented
Any update needed in this PR ?

2022-10-10 18:08 UTC, pbartholomew08 approved these changes

2022-10-10 18:09 UTC, merged