Rework on the example, include cuFFT and bug correction for CUDA-aware MPI/nccl
xcompact3d/2decomp-fft pull request #63
Opened 2022-09-27 11:50 UTC by rfj82982

Hi Guys I have put all the work on cuFFT and CUDA-aware MPI together and I have also merged with the latest version of the main. A substantial change is the rework of the examples now only 4 are available: halo, 2dtest, fft_physical in Z and fft_physical in Z. All of them works also on GPU however only 3 (the 2 fft and the transpose) have been really modified to work on GPU. 
i tested them using gnu 12 with mpich(mac) and openmpi with both generic and FFTW. For the GPU i tested NVHPC 22.7 with also NCCL. I would suggest for you to have a good look since changes might me quite large.

2022-09-27 12:05 UTC, mathrack commented
Thank you ! I will try to look at it deeply shortly. Please update

- [ ] the Makefile, I think it does not cover the cufft back-end yet
- [ ] the README to describe the GPU / NCCL preprocessor variables and the new optional dependency (cuFFT)
- [ ] please add error checks on each call to cuda functions

Cheers

2022-09-27 12:41 UTC, rfj82982 commented
The back-end for the cuFFT works. I have a direct path in the Makefile that i have to make more general. The remaining is with the compiler flags as well as the NCCL. For all these libs only the INC is needed

2022-09-27 12:58 UTC, mathrack commented on examples/fft_physical_x/Makefile
> +	valgrind --leak-check=full --show-leak-kinds=all mpirun -n 1 ./fft_physical_x 1 1
please replace `mpirun` with $(MPIRUN)

2022-09-27 13:00 UTC, mathrack commented on examples/fft_physical_x/Makefile
> +	valgrind --leak-check=full --show-leak-kinds=all mpirun -n 1 ./fft_physical_x 1 1
Similar comment for fft_physical_in_z

2022-09-27 13:11 UTC, mathrack commented
Using the nvidia compiler, is it possible to automatic compile the code with cufft and the GPU / NCCL flags ?

2022-09-27 13:15 UTC, rfj82982 commented
Yes I am writing how to do this in the README. Just use the following
`make CMP=nvhpc FFT=cufft PARAMOD=gpu CUFFT_PATH=/work4/scd/scarf562/eb-amd/software/NVHPC/22.7/Linux_x86_64/22.7/compilers`

2022-09-27 13:17 UTC, rfj82982 commented
CUDA-aware mpi and NCCL are activated by the FLAGS `_GPU` and `_NCCL`

2022-09-27 14:03 UTC, mathrack commented
I have tried to build the code with the provided `make` command but it keeps failing. See [this](https://github.com/xcompact3d/2decomp-fft/actions/runs/3136181962/jobs/5092773158) for instance.

I will try to fix it shortly, or will remove the GPU build from the automatic tests

2022-09-28 07:22 UTC, mathrack commented
A few extra minor comments.

I am not sure removing the IO tests is sharp because they are fixed and used in https://github.com/xcompact3d/2decomp-fft/pull/20. And the IO branch, when ready, will be merged. However, the tests are present there. Thus, even if we remove them here, we can restore them later. To be discussed.

In the test `fft_physical_in_x`, the following calling sequence is performed : `decomp_2d_fft_init`, test complex FFT, `decomp_2d_fft_finalize`, `decomp_2d_fft_init`, test real-complex and complex-real FFT, `decomp_2d_fft_finalize`. In my opinion, the expected usage for the 2decomp is `decomp_2d_fft_init` at the beginning of the program and `decomp_2d_fft_finalize` at the end. I am not sure it is sharp to test a program performing several fft_init / fft_finalize.

2022-09-28 16:13 UTC, pbartholomew08 requested changes

2022-09-28 16:13 UTC, pbartholomew08 commented on examples/fft_physical_x/Makefile
> +NP ?= 4
Default to 1

2022-09-28 16:13 UTC, pbartholomew08 commented on examples/fft_physical_z/Makefile
> +NP ?= 4
Defauly to 1

2022-09-28 16:13 UTC, pbartholomew08 commented on examples/test2d/Makefile
> +NP ?= 2
Default to 1

2022-09-28 16:13 UTC, pbartholomew08 commented on src/transpose_z_to_y.f90
> +    integer :: istat
Guard definition by ```_GPU```

2022-09-28 16:19 UTC, pbartholomew08 commented on src/transpose_z_to_y.f90
> +    integer :: istat
My mistake - it is guarded

2022-09-28 16:28 UTC, pbartholomew08 approved these changes

2022-09-28 16:39 UTC, merged